version: '3.9'

services:
  syllabusapi:
    image: syllabusapi:dev
    build:
      context: .
      dockerfile: SyllabusAPI/Dockerfile
    ports:
      - "8080:80"             # localhost:8080 → container :80
    volumes:
      - ./SyllabusAPI:/app    # hot‑reload while coding
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - syllabus-net

networks:
  syllabus-net:
    driver: bridge
