version: '3.9'

services:
  syllabusapi:
    image: syllabusapi:dev
    build:
      context: .
      dockerfile: SyllabusAPI/Dockerfile
    ports:
      - "8080:80"   # exposed API port
    volumes:
      - ./SyllabusAPI:/app
    networks:
      - syllabus-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal;Database=SyllabusManagmentDb;User Id=sql_user;Password=1234;

networks:
  syllabus-net:
